import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * API reference sidebar.
 *
 * Autogenerated from the `api/` directory, which `scripts/gen-api.mjs` fills
 * from the C# sources (`npm run gen:api`). One category per namespace, ordered
 * by the `position` in the `_category_.json` the script writes - so new types
 * and namespaces show up without touching this file.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
