import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Tutorials sidebar.
 *
 * The whole `tutorials/` tree is generated by `npm run sync:vault` from the
 * Obsidian vault, so the sidebar is autogenerated too - ordering comes from the
 * `_category_.json` files and the `sidebar_position` front matter written by the
 * sync script.
 */
const sidebars: SidebarsConfig = {
  tutorialsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
