import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * API reference sidebar.
 *
 * Autogenerated from the `api/` directory so that whatever the SDK doc
 * generator emits shows up without touching this file. If the generator ships
 * its own sidebar file (TypeDoc and DocFX both can), replace the entry below
 * with e.g.:
 *
 *   apiSidebar: require('./api/typedoc-sidebar.cjs'),
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
